/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.zpharma.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SiteConfig service. Represents a row in the &quot;ZUELLIG_SiteConfig&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.zpharma.model.impl.SiteConfigModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.zpharma.model.impl.SiteConfigImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SiteConfig
 * @generated
 */
@ProviderType
public interface SiteConfigModel
	extends BaseModel<SiteConfig>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a site config model instance should use the {@link SiteConfig} interface instead.
	 */

	/**
	 * Returns the primary key of this site config.
	 *
	 * @return the primary key of this site config
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this site config.
	 *
	 * @param primaryKey the primary key of this site config
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the site config ID of this site config.
	 *
	 * @return the site config ID of this site config
	 */
	public long getSiteConfigId();

	/**
	 * Sets the site config ID of this site config.
	 *
	 * @param siteConfigId the site config ID of this site config
	 */
	public void setSiteConfigId(long siteConfigId);

	/**
	 * Returns the group ID of this site config.
	 *
	 * @return the group ID of this site config
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this site config.
	 *
	 * @param groupId the group ID of this site config
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this site config.
	 *
	 * @return the company ID of this site config
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this site config.
	 *
	 * @param companyId the company ID of this site config
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this site config.
	 *
	 * @return the user ID of this site config
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this site config.
	 *
	 * @param userId the user ID of this site config
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this site config.
	 *
	 * @return the user uuid of this site config
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this site config.
	 *
	 * @param userUuid the user uuid of this site config
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this site config.
	 *
	 * @return the user name of this site config
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this site config.
	 *
	 * @param userName the user name of this site config
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this site config.
	 *
	 * @return the create date of this site config
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this site config.
	 *
	 * @param createDate the create date of this site config
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this site config.
	 *
	 * @return the modified date of this site config
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this site config.
	 *
	 * @param modifiedDate the modified date of this site config
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the show custom user registration of this site config.
	 *
	 * @return the show custom user registration of this site config
	 */
	public Boolean getShowCustomUserRegistration();

	/**
	 * Sets the show custom user registration of this site config.
	 *
	 * @param showCustomUserRegistration the show custom user registration of this site config
	 */
	public void setShowCustomUserRegistration(
		Boolean showCustomUserRegistration);

	/**
	 * Returns the site email address of this site config.
	 *
	 * @return the site email address of this site config
	 */
	@AutoEscape
	public String getSiteEmailAddress();

	/**
	 * Sets the site email address of this site config.
	 *
	 * @param siteEmailAddress the site email address of this site config
	 */
	public void setSiteEmailAddress(String siteEmailAddress);

	/**
	 * Returns the site phone number of this site config.
	 *
	 * @return the site phone number of this site config
	 */
	public long getSitePhoneNumber();

	/**
	 * Sets the site phone number of this site config.
	 *
	 * @param sitePhoneNumber the site phone number of this site config
	 */
	public void setSitePhoneNumber(long sitePhoneNumber);

	/**
	 * Returns the openinghours of this site config.
	 *
	 * @return the openinghours of this site config
	 */
	@AutoEscape
	public String getOpeninghours();

	/**
	 * Sets the openinghours of this site config.
	 *
	 * @param openinghours the openinghours of this site config
	 */
	public void setOpeninghours(String openinghours);

	/**
	 * Returns the copyright of this site config.
	 *
	 * @return the copyright of this site config
	 */
	@AutoEscape
	public String getCopyright();

	/**
	 * Sets the copyright of this site config.
	 *
	 * @param copyright the copyright of this site config
	 */
	public void setCopyright(String copyright);

}